version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  
  backend:
    build: 
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: email_guesser

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email_guesser
    volumes:
      - ./db:/var/lib/postgresql/data